### ISSUE TITLE
Adicionar opção para a moeda de Cabo Verde

### ISSUE THREAD

**Issue by theuves** [theuves/extenso.js#13]
Sou de Cabo Verde aonde se fala portugues, sugiro que o **_current.type_** também tenha  opção de personalizar para outras moedas por exemplo "quarenta e dois escudos" escudos é a moeda que se usa aqui

_Originally posted by @natalio in https://github.com/theuves/extenso.js/issues/10#issuecomment-455126026_

**Comment by theuves** [comment]
Oi @natalio,

Tu poderias dar algumas informações acerca da escrita dos valores monetários de Cabo Verde?

Vi na Wikipédia que o código *ISO* é CVE e que vocês têm notas de 200, 500, 1.000, 2.000 e 5.000 escudos e moedas de 1, 5, 10, 20, 50 e 100 escudos. Como vocês escrevem isso?

Por exemplo:

- **1 CVE** = 1 escudo?
- **2 CVE** = 2 escudos?

Como vocês escrevem as subunidades da moeda?

- **2,50 CVE** = dois escudos e cinquenta centavos?

**Comment by natalio** [comment]
isso @theuves
