### ISSUE TITLE
ERROR in extenso.min.js from UglifyJs 

### ISSUE THREAD

**Issue by natalio** [theuves/extenso.js#17]
me da um erro ao fazer builder

**Comment by guesant** [comment]
@theuves o que acha de usar o typescript?

**Comment by theuves** [comment]
*(Problema reportado na [issue 19](https://github.com/theuves/extenso.js/issues/19#issuecomment-515082278) também.)*

**Comment by theuves** [comment]
Estou verificando o problema ao fazer o build, se alguém souber de algo avise.

**Comment by theuves** [comment]
> @theuves o que acha de usar o typescript?

Não sei, teriamos que modificar muita coisa no projeto e eu não tenho tanto domínio em TypeScript.

TypeScript é interessante, mas está sendo o meu foco no momento.

**Comment by theuves** [comment]
Tem algum ponto forte para defender o uso de TypeScript?

**Comment by guesant** [comment]
> Estou verificando o problema ao fazer o build, se alguém souber de algo avise.

já corrigi o erro, irei mandar um pull request

**Comment by guesant** [comment]
posso atualizar os pacotes?

**Comment by guesant** [comment]
>Não sei, teriamos que modificar muita coisa no projeto e eu não tenho tanto domínio em TypeScript.

é ai que está o pulo do gato ;)
eu sugeri o typescript como uma alternativa se o babel+webpack não funcionassem, e sim, tem como usar typescript sem tipagem

**Comment by theuves** [comment]
Resolvido no PR #20 (by @guesant).
