### ISSUE TITLE
Escalas curta e longa

### ISSUE THREAD

**Issue by guesant** [theuves/extenso.js#19]
Olá, Matheus! Primeiramente obrigado pelo projeto,  que com certeza irei utilizar.

Mas eu vim aqui relatar que há uma pequena diferença na nomenclatura de escalas pt_PT/pt_BR 

---

![Screenshot_20190723-210410~2](https://user-images.githubusercontent.com/43099880/61757203-9d25b980-ad8d-11e9-88f9-78e3a4c9a94a.png)

Resumidamente, o "nosso" bilhão é mil milhões em Portugal, nosso trilhão é bilião etc

![Screenshot_20190723-211306~2](https://user-images.githubusercontent.com/43099880/61757606-45884d80-ad8f-11e9-8877-355a56012f05.png)

<p style="text-align: right">

[_Wikipedia – Escalas curta e longa_](https://pt.wikipedia.org/wiki/Escalas_curta_e_longa)

</p>

---

Eu não acredito que isso seja um problema urgente - até porque meu alvo é pt_BR - mas como tem a opção `locale`, acredito que devemos pensar em uma possível solução para isso.

Desde já agradeço!
Gabriel Rodrigues

**Comment by theuves** [comment]
Interessante, não havia reparado isso.

Vou dar mais algumas estudas aqui e assim que possível inicio as alterações (ou se tiver disponibilidade, você pode submeter um Pull Request).

**Comment by theuves** [comment]
@natalio pode confirmar como é a escrita em Cabo Verde?

**Comment by gabrodbr** [comment]
Eu não sei como fica a questão da globalização, mas segue uma lista dos países e suas escalas ![jooj](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/World_map_of_long_and_short_scales.svg/512px-World_map_of_long_and_short_scales.svg.png)

**Comment by gabrodbr** [comment]
@theuves estou pensando em usar algo com o 

Vamos supor que tenhamos o número 1.000.000.000

Poderíamos usar o Decimal.js de comparação para ver a quantidade de casas que tem no número.

| _e_ | br | pt |
| :------------- | :----------: | -----------: |
| ^9 | bilhão  | mil milhões    |
| ^12   | trilhão | | bilião |

eu sei que isso parece óbvio, mas vou tentar "implementar" isso ao código 🙃

**Comment by theuves** [comment]
> eu sei que isso parece óbvio, mas vou tentar "implementar" isso ao código 🙃

Opa, @gabrodbr, ótimo!

Antigamente ele aceitava a representação científica, do próprio JavaScript, ou seja:

```js
extenso("1e+3"); // 'mil'
```

Mas eu acabei removendo devido a logistica duma nova implementação.

Sinta-se livre para implementar e mandar um PR.

**Comment by guesant** [comment]
@theuves eu estou recebendo um erro quanto rodo `npm run build`:

```
ERROR in extenso.min.js from UglifyJs
Unexpected token: keyword (const) [extenso.min.js:116,0]
```

**Comment by guesant** [comment]
Olá, Matheus! 

Me desculpe a demora, nesse meio tempo eu estava em um momento ocupado, e, quando fiquei "livre", foquei em outros projetos

Mas isso não foi algo ruim. Pelo contrário, eu aprendi muita coisa de lá pra cá. Inclusive os testes deste projeto me ajudaram a chegar à uma solução dessa issue.

Por conta do hacktoberfest, eu lembrei dessa issue em aberta. Mas para compensar minha falta, quero que, se for aceitar o PR, revise antes de outubro ou após o mesmo. É claro, só se você quiser 

----

Antes de eu mandar um PR, eu queria saber se tem algum guia de estilo para seguir (ou devo me basear no já presente nos arquivos).

Obrigado!

**Comment by guesant** [comment]
Agora que vi aqui no readme, em breve eu mando o pr

**Comment by theuves** [comment]
Escalas adicionadas no PR #29.
