### ISSUE TITLE
Valores monetários com uma casa decimal devolve texto incorreto.

### ISSUE THREAD

**Issue by sarabando** [theuves/extenso.js#22]
Este exemplo: 
extenso("6.5", { locale: 'pt', mode: 'currency', currency: { type: 'EUR' } })
devolve ""seis euros e cinco cêntimos""
onde deveria estar 
"seis euros e cinquenta cêntimos"

no meu cenário corrigi da segunte forma 
var valor = parseFloat('6.5').toFixed(2);
var valorExtenso = extenso(valor, { locale: 'pt', mode: 'currency', currency: { type: 'EUR' } });

**Comment by theuves** [comment]
Realmente, isso foi um erro de planejamento.

Os testes foram escritos de modo errado, onde foi considerado os zeros à direita.

https://github.com/theuves/extenso.js/blob/a78408039f22bb351e156425a7dad0fad8562ed3/src/write-currency/index.test.js#L25-L26

**Comment by theuves** [comment]
Estou a corrigi-lo.

**Comment by theuves** [comment]
Problema corrigido em 24a4d5e6c77671fe5e6fed7834b318c7a5bbd883.

Muito obrigado @sarabando!!!

**Comment by sarabando** [comment]
Foi bom poder te ajudar. @theuves
