### ISSUE TITLE
Problema com números fracionários

### ISSUE THREAD

**Issue by Matheusih** [theuves/extenso.js#25]
Os exemplos com números fracionários do README estão retornando `Error: Invalid number`

Os exemplos:
```
extenso('3.14') // 'três inteiros e quatorze centésimos'
extenso('3.14', { number: { decimal: 'formal' } }) // 'três inteiros e quatorze centésimos'
extenso('3.14', { number: { decimal: 'informal' } }) // 'três vírgula quatorze'
```

O erro:
```
webpack://extenso/./src/write-all.js?:56
    throw new Error('Invalid number');
    ^

Error: Invalid number
    at eval (webpack://extenso/./src/write-all.js?:56:11)
    at main (/home/matheus/test/random/index2.js:4:13)
    at Object.<anonymous> (/home/matheus/test/random/index2.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by Eliada** [comment]
Same issue here:
the doc could be correct at least

**Comment by WillianRod** [comment]
Mesmo problema aqui

**Comment by theuves** [comment]
@Matheusih, como o @WillianRod disse (na versão 2.0.1) você deve passar `,` no lugar de `.`.

O @Eliada abriu um PR #27 corrigindo o exemplo na documentação.

**Comment by theuves** [comment]
Devo confessar agora que está um pouco restritivo com essa opção, principalmente depois que comecei a internacionalizar a biblioteca (adicionando suporte para Portugal, Moçambique e Angola).

**Comment by theuves** [comment]
A questão é que o ponto (`.`) é usado aqui (no Brasil) como serpardor de números maiores que mil (como formatador) e não como separador de inteiros e decimais.

Ex.: 1.000,00 = mil

Realmente isso pode causar um problemas se for passado o valor como float.

Talvez a gente deva rever as definições dos separadores com base na localização.

@amandio e @osvaldoM como é em Moçambique?

Vocês usam oficialmente ponto (`.`) ou vírgula (`,`) para separar decimais?

**Comment by osvaldoM** [comment]
Ao inserir valores, em Moçambique usamos tanto o ponto como a vírgula(
intercambiavelmente) para separar números inteiros e decimais.

> Talvez a gente deva rever as definições dos separadores com base na localização.

Não tenho certeza se esta seria uma opção razoável. Mesmo que a pessoa esteja no Brazil, dependendo das configurações do computador(O meu computador por ex. está em inglês), o browser pode usar o ponto(.) como separador de inteiros e decimais.(veja: https://stackoverflow.com/a/13416324/4043487)

**Comment by theuves** [comment]
Adicionei na PR #31 a opção de escolher qual separador decimal será usado (consequentemente qual será o separador de milhar).

Passou a ser aceito também números decimais do JavaScript (*floats*).

**Comment by neuberoliveira** [comment]
me corrijam se estiver errado, mas essa PR ainda nao foi para o npm certo?

ultima versao 2.01
https://github.com/portujs/extenso.js/blob/2.0.1/src/write-all.js#L75

master
https://github.com/portujs/extenso.js/blob/master/src/write-all.js#L73

e nao tem previsao para esse fix subir nao??
