### ISSUE TITLE
Considerar usar .npmignore para filtrar o que é publicado

### ISSUE THREAD

**Issue by lubien** [theuves/extenso.js#32]
Talvez coisas como webpack.config.js etc não devam ir.

**Comment by theuves** [comment]
Esses arquivos não são publicados!

Eu já faço essa configuração diretamente no `package.json` pela propriedade `.files`.

Veja abaixo:

https://github.com/theuves/extenso.js/blob/beda49ff3acdd79d61c5015441bc0ffe5d08e4e1/package.json#L6-L8

*(Mais informações sobre `.files` [aqui](https://docs.npmjs.com/files/package.json#files).)*

Da uma olhada no [unpkg.com](https://unpkg.com) como está publicado a versão 2.0.1 [[*link*](https://unpkg.com/browse/extenso@2.0.1/)]:

![Screenshot do unpkg.com](https://user-images.githubusercontent.com/10136242/85411411-5361c800-b536-11ea-9ffb-c245e73d0c09.png)

**Comment by theuves** [comment]
Confirma se era sobre isso mesmo que você estava se referindo, por favor.

**Comment by lubien** [comment]
Perfeito! 

Não sabia que isso poderia ser feito no package.json, good job.

**Comment by theuves** [comment]
Tranquilo, muito obrigado!

Uma nova versão será lançada em breve.
