### ISSUE TITLE
Retorno do valor 0

### ISSUE THREAD

**Issue by leofrederiche** [theuves/extenso.js#33]
Quando passo:
extenso(0, { mode: 'currency' }) 
#=> zero centavos

Mas com:
extenso(0)
#=> undefined

**Comment by theuves** [comment]
Ótima observação!

Vou verificar assim que eu tiver um tempo.

Se se sentir à vontade pode enviar um _Pull Request_.

**Comment by theuves** [comment]
Obrigado @leofrederiche!!!
