### ISSUE TITLE
Extenso com reais e/ou centavos?

### ISSUE THREAD

**Issue by yusser** [theuves/extenso.js#4]
Que tal escrever o valor já com a(s) palavra(s) reais e/ou centavos?
Se concordar, faço um pull request.

**Comment by theuves** [comment]
Hey @yusser , fechou ☹️?!

Sim, sim 👍. Eu estava planejando fazer algo do tipo, mas estava com preguiça (já faz 10 meses que não faço nada nele ― o código tá bem sujo 😳). Eu estava planejando reescrevê-lo modularizando-o e usando ES6 para depois "transpilá-lo" com Babel.

Eu pretendia manter a escrita normal dos números como principal funcionalidade. E deixar a escrita em reais dentro dentro de uma opção, ou qualquer coisa do tipo.

Fique a vontade se você quiser mandar um PR ✌️.

**Comment by theuves** [comment]
Vou manter essa issue aberta, mesmo se você tenha desistido de contribuir com o código.

Quando tudo tiver pronto eu fecho-a.

**Comment by yusser** [comment]
Matheus, eu fechei por outro motivo... Após executar sua função, fiz um replace de inteiro pra reais e de centésimos para centavos. Quanto a modularizar e usar babel acho importante, pq o códifo fica mais flexível.

Não pensei em refatorar seu cógido. Mas, vou avaliar esta possibilidade.
