### ISSUE TITLE
Pacote não publicado no NPM

### ISSUE THREAD

**Issue by cleever** [theuves/extenso.js#5]
Aparentemente a publicação npm desse pacote está desatualizada.

Alguma previsão de publicar as novas features para o npm em uma nova versão?

**Comment by Tjdestroyer** [comment]
Também vi a mesma questão, os numeros em "real" não estão funcionando para a versao do NPM.

> 
> 
> Aparentemente a publicação npm desse pacote está desatualizada.
> 
> Alguma previsão de publicar as novas features para o npm em uma nova versão?

**Comment by theuves** [comment]
Olá,

Desculpe-me a demora, passeis vários meses longe dos códigos.

Realmente o pacote não tinha sido publicado no NPM - e eu não me lembro o motivo.

Mas, agora está publicado.

[Versão 1.0.0](https://github.com/theuves/extenso.js/releases/tag/1.0.0) ⚡️

Obrigado!
